"""initial_schema

Revision ID: f26172890c3a
Revises: 
Create Date: 2026-03-22 13:17:15.405189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f26172890c3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('business_logo', sa.Text(), nullable=True),
    sa.Column('default_forecast_period', sa.Integer(), nullable=True),
    sa.Column('default_confidence_level', sa.String(), nullable=True),
    sa.Column('holiday_calendar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_logs_user_created', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('time_granularity', sa.String(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('seasonality_mode', sa.String(), nullable=True),
    sa.Column('selected_model', sa.String(), nullable=True),
    sa.Column('demand_profile', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('wape', sa.Float(), nullable=True),
    sa.Column('smape', sa.Float(), nullable=True),
    sa.Column('mase', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('data_start_date', sa.Date(), nullable=True),
    sa.Column('data_end_date', sa.Date(), nullable=True),
    sa.Column('data_row_count', sa.Integer(), nullable=True),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tuned_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('share_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecasts_user_product', 'forecasts', ['user_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_product_id'), 'forecasts', ['product_id'], unique=False)
    op.create_index(op.f('ix_forecasts_share_token'), 'forecasts', ['share_token'], unique=True)
    op.create_index(op.f('ix_forecasts_user_id'), 'forecasts', ['user_id'], unique=False)
    op.create_table('sales_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Numeric(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('quantity_sold > 0', name='ck_sales_data_qty_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sales_data_user_date', 'sales_data', ['user_id', 'date'], unique=False)
    op.create_index('idx_sales_data_user_product', 'sales_data', ['user_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_sales_data_date'), 'sales_data', ['date'], unique=False)
    op.create_index(op.f('ix_sales_data_product_id'), 'sales_data', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_data_user_id'), 'sales_data', ['user_id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('lower_bound_80', sa.Float(), nullable=True),
    sa.Column('upper_bound_80', sa.Float(), nullable=True),
    sa.Column('lower_bound_95', sa.Float(), nullable=True),
    sa.Column('upper_bound_95', sa.Float(), nullable=True),
    sa.Column('trend', sa.Float(), nullable=True),
    sa.Column('weekly_seasonality', sa.Float(), nullable=True),
    sa.Column('yearly_seasonality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_results_forecast_id', 'forecast_results', ['forecast_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_forecast_results_forecast_id', table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_sales_data_user_id'), table_name='sales_data')
    op.drop_index(op.f('ix_sales_data_product_id'), table_name='sales_data')
    op.drop_index(op.f('ix_sales_data_date'), table_name='sales_data')
    op.drop_index('idx_sales_data_user_product', table_name='sales_data')
    op.drop_index('idx_sales_data_user_date', table_name='sales_data')
    op.drop_table('sales_data')
    op.drop_index(op.f('ix_forecasts_user_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_share_token'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_product_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_date'), table_name='forecasts')
    op.drop_index('idx_forecasts_user_product', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index('idx_activity_logs_user_created', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
